📅 コンテストの応募締切日を11/30に変更しました。
coderdojo-japan/dojocon2020.coderdojo.jp pull request #8
Opened 2020-11-19 12:32 UTC by hota1024

コンテストの応募締切日を11/30に変更しました。
レビューよろしくおねがいします。

2020-11-19 13:20 UTC, ymsg19 approved these changes
@hota1024 ありがとうございます！！
やってもらってて申し訳ないんですが、変更したログは残しておいた方が良いと思っていて、既存のものに打ち消し線で消して、延長しました！11/xx までです！みたいな感じにしていただけると良いのかな〜と思います！

2020-11-19 13:21 UTC, ymsg19 requested changes
ありがとうございます！！
やってもらってて申し訳ないんですが、変更したログは残しておいた方が良いと思っていて、既存のものに打ち消し線で消して、延長しました！11/xx までです！みたいな感じにしていただけると良いのかな〜と思います！

2020-11-20 08:35 UTC, hota1024 commented
募集締切日を延期したという趣旨の文を追加追加しました!
確認お願いします。

2020-11-20 08:42 UTC, ymsg19 approved these changes
LGTM!

2020-11-20 08:43 UTC, merged